class ScannerLocation < ApplicationRecord
  # Bogus constraint because rails (activerecord) insists on a pk
  self.primary_keys = [:steward_scanner_patient_log_id, :create_date]

  #set_sequence_name :autogenerated

  # Table relationships


  # Validations
  
end
